In [24]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [25]:
df = pd.read_csv("../data/raw/crop_yield_raw.csv")

df

,State,District,Crop,Season,Area,Rainfall,Temperature,Soil_Nitrogen,Fertilizer,Production,Yield
0,Punjab,Ludhiana,Wheat,Rabi,10,600,25,40,100,450,45
1,UP,Lucknow,Rice,Kharif,8,800,30,50,120,480,60
2,Maharashtra,Nashik,Sugarcane,Kharif,15,900,32,60,150,750,50
3,Gujarat,Ahmedabad,Cotton,Kharif,12,700,28,45,110,500,42
4,Punjab,Amritsar,Wheat,Rabi,9,550,24,35,90,390,43
5,UP,Kanpur,Rice,Kharif,7,750,29,48,115,420,60
6,Madhya Pradesh,Indore,Soybean,Kharif,11,650,27,42,100,440,40
7,Rajasthan,Jaipur,Cotton,Kharif,13,500,35,38,95,400,38

In [26]:
df.shape

(8, 11)

In [27]:
df.head()

,State,District,Crop,Season,Area,Rainfall,Temperature,Soil_Nitrogen,Fertilizer,Production,Yield
0,Punjab,Ludhiana,Wheat,Rabi,10,600,25,40,100,450,45
1,UP,Lucknow,Rice,Kharif,8,800,30,50,120,480,60
2,Maharashtra,Nashik,Sugarcane,Kharif,15,900,32,60,150,750,50
3,Gujarat,Ahmedabad,Cotton,Kharif,12,700,28,45,110,500,42
4,Punjab,Amritsar,Wheat,Rabi,9,550,24,35,90,390,43

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State          8 non-null      object
 1   District       8 non-null      object
 2   Crop           8 non-null      object
 3   Season         8 non-null      object
 4   Area           8 non-null      int64
 5   Rainfall       8 non-null      int64
 6   Temperature    8 non-null      int64
 7   Soil_Nitrogen  8 non-null      int64
 8   Fertilizer     8 non-null      int64
 9   Production     8 non-null      int64
 10  Yield          8 non-null      int64
dtypes: int64(7), object(4)
memory usage: 832.0+ bytes

In [29]:
df.describe()

,Area,Rainfall,Temperature,Soil_Nitrogen,Fertilizer,Production,Yield
count,8.00000,8.000000,8.000000,8.000000,8.00000,8.000000,8.000000
mean,10.62500,681.250000,28.750000,44.750000,110.00000,478.750000,47.250000
std,2.66927,133.463478,3.615443,7.941752,19.08627,115.812348,8.631338
min,7.00000,500.000000,24.000000,35.000000,90.00000,390.000000,38.000000
25%,8.75000,587.500000,26.500000,39.500000,98.75000,415.000000,41.500000
50%,10.50000,675.000000,28.500000,43.500000,105.00000,445.000000,44.000000
75%,12.25000,762.500000,30.500000,48.500000,116.25000,485.000000,52.500000
max,15.00000,900.000000,35.000000,60.000000,150.00000,750.000000,60.000000

In [30]:
df.isnull().sum()

State            0
District         0
Crop             0
Season           0
Area             0
Rainfall         0
Temperature      0
Soil_Nitrogen    0
Fertilizer       0
Production       0
Yield            0
dtype: int64

In [32]:
print(df.duplicated().sum())

0

In [33]:
df.to_csv(
"../data/processed/yield_processed.csv",
index=False
)

print("Dataset Saved")

Dataset Saved